export enum TypeIdentification {
  DNI = 'DNI',
  RUC = 'RUC',
  RUC_PERSON_NATURAL = 'RUC_PERSON_NATURAL',
  RUC_SOCIETY_PRIVATE = 'RUC_SOCIETY_PRIVATE',
  RUC_PUBLIC_SOCIETY = 'RUC_PUBLIC_SOCIETY',
  POSSIBLY_VALID_RUC = 'POSSIBLY_VALID_RUC',
}